[package]
name = "snotify"
version = "0.1.0"
authors = ["Mustafa <mustafasalih1991@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
notify-rust = "4.3.0"
dbus = "0.9.2"
dbus-tree = "0.9.1"